### ISSUE TITLE
consistently small domains

### ISSUE THREAD

**Issue by oursu** [kingsfordgroup/armatus#2]
Hi,
Thank you very much for all your help.

I am writing to ask for some advice on running Armatus.
I have run it on my dataset consisting of 40kb window interaction counts, following normalization by ICE. I then compared the domains I got with the domains in the Dixon et al. paper, as well as the HiC input data used to call these domains (image attached).
I consistently find sets of very small domains, even in places where the HiC data support a larger domain (e.g. at the region 6 000 000 - 8 000 000). I wanted to check whether you could advise me about why I am getting such a behavior, and how I could proceed.

Thank you,
Oana
![tads_40kb_hic_first10mb](https://cloud.githubusercontent.com/assets/5633306/5927948/7adecd44-a62b-11e4-99f7-6f76143ec47f.jpg)

**Comment by oursu** [comment]
here is a picture of a larger genomic region at the same site
![tads40kb_hic20first20mb](https://cloud.githubusercontent.com/assets/5633306/5928037/6f9f205e-a62c-11e4-8235-0ec717980c27.png)

**Comment by lynxoid** [comment]
Hi Oana,

Thank you for brining up this interesting point to our attention. There are potentially several ways to go about this:
- try finer resolutions for gamma
- explore alt. opt and near opt solutions (-k parameter)
- run the algorithm before normalizing the matrix with ICE
- it may be that the domain quality is below the mean for domains of that size (it does seem very pale pink which suggests low frequencies), and is never selected as part of the solution.

Additionally, Dixon et al. directionality index used to find domains has an explicit parameter of 2Mb (discussed in their Supp. material, p. 6-7) which could contribute to the results you see w/ their method.

Hope this helps and please let us know if there is anything else!
