### ISSUE TITLE
Armatus 2.1 example

### ISSUE THREAD

**Issue by latkins** [kingsfordgroup/armatus#4]
I am probably doing something wrong, but I can't get the example "clustering1.gz" to work with the Armatus 2.1 binary.

```bash
lpa24:~/dev/util/armatus/examples$ armatus -i clustering1.gz -g 1 -o test -m -r 40000
Multiresoultion ensemble will be written to files
Reading input from clustering1.gz.
N/A at resolution 40000bp
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stod
Aborted
```

I have tried to follow the format of the example given in the readme, but clearly something is not right. I have tried a number of variations on the above, none of which seem to work.

**Comment by kingsfordgroup** [comment]
Hi,

I think the issue is that Armatus is expecting a matrix without any labels on the rows, but clustering1.gz has row labels. If you remove the row labels, Armatus runs without error. We’ll have to update the readme, etc. Thanks for pointing this out.

Carl

**Comment by latkins** [comment]
That seems to have been the issue. Thanks!
