### ISSUE TITLE
Compiling on Ubuntu

### ISSUE THREAD

**Issue by johnstonmj** [kingsfordgroup/armatus#8]
I just finished compiling on Ubuntu and I found a couple issues I wanted to relay to you:

**1 - Order of boost flags**
I was following the instructions to compile in the README.md.

> Here is one-liner to compile Armatus with G++ given you have the proper dependencies:
> 
>  `g++ -std=c++11 -w -lboost_system -lboost_iostreams -lboost_program_options -L /opt/local/lib/ -I include/ -I /opt/local/include/ -O3 -o binaries/armatus-linux-x64 src/*.cpp `

In order to make it work, I had to modify this line to:
`g++ -std=c++11 -w -L /opt/local/lib/ -I include/ -I /opt/local/include/ -O3 -o binaries/armatus-linux-x64 src/*.cpp -lboost_iostreams -lboost_program_options -lboost_system`

From reading forums, apparently the boost linker flags work better if they are after the src/*.cpp

Additionally, I had to make an empty directory "binaries" for the output to land in before this line would run.

**2 - Help message upon install**

After compiling what I believe to be armatus-2.2 from
https://github.com/kingsfordgroup/armatus/archive/v2.2.tar.gz

I tested by looking at the help message
`./armatus-linux-x64 -h`

and I was greeted by
`****        ARMATUS 2.1        ****`
rather than the expected 2.2.

Does the help message need an update, or did I get an older version than I had intended?

Thanks for your help! Looking forward to using Armatus!

**Comment by ckingsford** [comment]
Thanks! I updated the one-liner. The "2.1" in the banner is wrong, and I've updated that too.
